### ISSUE TITLE
Error with ES Module import when using AdonisJS with AdminJS

### ISSUE THREAD

**Issue by MorganChetelat** [chirgjin/adminjs-adonis#11]
Description:

I'm currently using AdonisJS alongside AdminJS. When I try to run the server, I'm faced with the following error:

``` Bash
Error: require() of ES Module /my-project-folder/node_modules/adminjs/index.js from my-project-folder/node_modules/adminjs-adonis/build/providers/AdminProvider.js not supported.
Instead change the require of index.js in my-project-folder/node_modules/adminjs-adonis/build/providers/AdminProvider.js to a dynamic import() which is available in all CommonJS modules.
```

I'm still getting familiar with the intricacies of CommonJS and ES modules, so I apologize if this issue is not directly related to the package itself. However, any guidance or clarification on this matter would be highly appreciated.

**Comment by watzon** [comment]
Seems like this might be the issue https://docs.adminjs.co/installation/getting-started#esm-and-cjs-support
Since the installation command in the readme calls for just installing `adminjs` without a pinned version we end up getting the ESM version of the package now. The easy fix would be to just pin a version, `npm i adminjs@6.8.7`.

**Comment by chirgjin** [comment]
Thanks for the PR @watzon 
@MorganChetelat I'd also recommend using v6 for now as adonis doesn't fully support ESM yet

**Comment by chirgjin** [comment]
Hey @MorganChetelat I've merged watzon's PR and you can now follow the instructions in readme to install adminjs :)

**Comment by chirgjin** [comment]
I'm marking this issue as closed for now. Feel free to re-open it if any issue arises

**Comment by MorganChetelat** [comment]
Thanks @chirgjin and @watzon for your help ;)

**Comment by TDodgeCo** [comment]
Just FYI - the docs appear to still be pointing to 6.0.0, which causes this issue.
