### ISSUE TITLE
Unclear how to handle attachments in adminjs

### ISSUE THREAD

**Issue by webspaceadam** [chirgjin/adminjs-adonis#16]
Dear adminjs-adonis Maintainers,

I'm reaching out to address an issue encountered when attempting to integrate the `attachment-lite` package with adminjs-adonis, as per the model customization options outlined in the [readme](https://github.com/chirgjin/adminjs-adonis#model-customization). 

The `attachment-lite` package is my chosen library for handling attachments. Successfully integrating it within my controllers, I specified the `type: "file"` within the `@adminColumn` decorator to accommodate file attachments as illustrated in the following `Product` model excerpt:

```typescript
// ... [other model properties]

@adminColumn({
  type: "file",
  serialize: () => {
    console.log("serialize");
  },
})
@attachment()
public image: AttachmentContract;

// ... [other model relationships and properties]
```

While the files are being accepted as anticipated, persisting the model via save operations triggers a `500 Internal Server Error`, stemming from the Lucid ORM. Efforts to mitigate this via additional hooks and custom serialization functions have unfortunately not borne fruit.

In light of this, I would like to inquire if there's an existing workaround or configuration that supports `attachment-lite` within adminjs-adonis. If such functionality is currently absent, could you guide me on how to extend the adapter to incorporate this feature? I am eager and willing to contribute to the development of this capability.

Your guidance and support would be greatly appreciated.

Thank you for your attention to this matter.

Best regards,
Adam

**Comment by chirgjin** [comment]
Hi @webspaceadam 
This package does have support for attachments but it doesn't specifically support attachment-lite yet.
For adding support of attachment-lite we can have a plugin like system for adminjs maybe but I haven't really thought about this in detail

You can try adding this hook to your model: 
```ts
import { File } from '@adonisjs/bodyparser/build/src/Multipart/File'
import {
    Attachment,
    attachment,
    AttachmentContract,
} from '@ioc:Adonis/Addons/AttachmentLite'
import {
    adminColumn,
    beforeCreate,
    beforeUpdate,
} from '@ioc:Adonis/Addons/AdminJS'

// ... [other model properties]

@adminColumn({
  type: "file",
  serialize: () => {
    console.log("serialize");
  },
})
@attachment()
public image: AttachmentContract;

/**
 * AdminJS takes files as Multipart file object instead of Attachment class.
 * So we convert them to Attachment objects before saving.
 */
@beforeCreate()
@beforeUpdate()
public static async convertAttachments(instance: Product) {
    if (instance.$dirty.image && instance.image instanceof File) {
        instance.image = Attachment.fromFile(instance.image)
    }
}

// ... [other model relationships and properties]
```
If you still have any issues / errors then please do include a screenshot of the error that you get
It'd help me in debugging the issue :)

**Comment by webspaceadam** [comment]
This conversion works! 

I had to remove the check for the `instaceof File` as at least my version of adonis does not have the file type you described within the bodyparser package. but does not matter. For the current state of development that is totally fine. Thank you very much :)
